baseurl = "mateuszjarzyna.github.io"
languageCode = "en-us"
title = "Mateusz Jarzyna"
theme = "hello-friend"
copyright = ""
paginate = 5

[params]
  subtitle = "modest blog"

[params.logo]
  logoText = "Mateusz Jarzyna"
#   or
#
#   path = "/img/your-example-logo.svg"
#   alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "showcase"
    name = "Showcase"
    url = "/showcase"
